### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by mimi1vx** [Soostone/rotating-log#1]
Hello,

cabal file states BSD-3-Clause licence, But LICENSE file has only:

"All rights reserved"

please clarify license .

**Comment by peti** [comment]
Yes, :+1:! Please make sure the license tag and the LICENSE file say the same thing. As is, this package is technically speaking not free software.

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by MichaelXavier** [comment]
Uploaded as version [0.4.1](http://hackage.haskell.org/package/rotating-log-0.4.1).

**Comment by peti** [comment]
Thanks.
